
 
 name: CI
 
 on: 
  pull_request: 
     branches: [main]
  push:
     branches: [main]

 jobs:
    validate-configs:
       runs-on: ubuntu-latest
       steps:
        - name: Checkout code
          uses: actions/checkout@v4

        -  name: Set up Python
           uses: actions/setup-python@v5
           with:
             python-version: "3.12"

        - name: Install validation tool
          run: pip install check-jsonschema
        
        - name: Validate all environment configs
          run: |
            for file in configs/examples/*.yaml; do
             echo "Validating $file"
             check-jsonschema --schemafile schemas/environment-request.schema.json "$file"
            done      
 
    terraform-apply-prod:
      needs: validate-configs
      runs-on: ubuntu-latest
      environment: production
      if: github.ref == 'refs/heads/main'
      defaults:
         run:
            working-directory: terraform
      steps:
       -  name: Checkout code
          uses: actions/checkout@v4
      
       -  name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: us-east-1

       -  name: Setup Teraaform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.15.8

       -  name: Terraform Init
          run: terraform init

       -  name: Terraform Plan
          run: terraform plan -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
 
       -  name: Terraform Apply
          run:  terraform apply -auto-approve

